apiVersion: apps/v1
kind: Deployment
metadata:
  name: regretan-operator-scheduler
  namespace: regretan
  labels:
    app.kubernetes.io/name: regretan-operator-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: regretan-operator-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: regretan-operator-scheduler
    spec:
      serviceAccountName: regretan-operator
      containers:
        - name: regretan-operator-scheduler
          image: "deftfitf/regretan:0.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: app
              containerPort: 8080
            - name: actuator
              containerPort: 8081
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
              scheme: HTTP
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: actuator
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGRETAN_ROLE
              value: scheduler
            - name: REGRETAN_MYSQL_JDBC_URL
              value: "jdbc:mysql://my-release-mysql-headless.regretan.svc.cluster.local:3306/regretan?allowPublicKeyRetrieval=true&useSSL=false&useAffectedRows=true"
            - name: REGRETAN_MYSQL_USER
              value: regretan
            - name: REGRETAN_MYSQL_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: regretan-scheduler
  namespace: regretan
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: regretan-operator-scheduler
  type: ClusterIP
